In [1]:
import numpy as np
import dpJoshi

In [2]:
dir(dpJoshi)

['Antithetic',
 'BlackScholesCall',
 'BlackScholesCallVega',
 'BlackScholesDigitalCall',
 'BlackScholesDigitalPut',
 'BlackScholesPut',
 'CashFlow',
 'ConvergenceTable',
 'ExoticBSEngine',
 'ExoticEngine',
 'MJArray',
 'Parameters',
 'ParametersConstant',
 'ParametersInner',
 'PathDependent',
 'PathDependentAsian',
 'PayOff',
 'PayOff1',
 'PayOff3',
 'PayOffBridge',
 'PayOffCall',
 'PayOffCall3',
 'PayOffDD',
 'PayOffDD3',
 'PayOffForward',
 'PayOffPut',
 'PayOffPut3',
 'RandomBase',
 'RandomParkMiller',
 'SimpleBinomialTree',
 'StatisticsMC',
 'StatisticsMean',
 'TreeAmerican',
 'TreeEuropean',
 'TreeProduct',
 'Vanilla1',
 'Vanilla2',
 'Vanilla3',
 'WrapperPathDependent',
 'WrapperRandom',
 'WrapperStats',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'simpleMC1',
 'simpleMC2',
 'simpleMC3',
 'simpleMC4',
 'simpleMC5',
 'simpleMC6',
 'simpleMC7',
 'simpleMC8']

# Chapter 1: Testing of SimpleMonteCarlo1 procedural function

In [3]:
Expiry = 1.;
Strike = 100;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 100000;
    
    
result = dpJoshi.simpleMC1(Expiry, Strike, Spot, Vol, r, NumberOfPaths);

In [4]:
result

10.489101071914316

# Chapter 3: Testing of SimpleMonteCarlo2 procedural function

In [5]:
callPayOff = dpJoshi.PayOff1(100, dpJoshi.PayOff1.call)
putPayOff = dpJoshi.PayOff1(100, dpJoshi.PayOff1.put)

Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 100000;

In [6]:
resultCall = dpJoshi.simpleMC2(callPayOff, Expiry, Spot, Vol, r, NumberOfPaths);
resultPut = dpJoshi.simpleMC2(putPayOff, Expiry, Spot, Vol, r, NumberOfPaths);

In [7]:
resultCall

10.47436669067924

In [8]:
resultPut

5.5559632048892515

# Chapter 3: Testing of SimpleMonteCarlo2 with virtual inheritance for PayOff class

In [9]:
callPayOff = dpJoshi.PayOffCall(100)
putPayOff = dpJoshi.PayOffPut(100)
doubleDigitalPayOff = dpJoshi.PayOffDD(100,120)

Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 100000;

In [10]:
resultCall = dpJoshi.simpleMC2(callPayOff, Expiry, Spot, Vol, r, NumberOfPaths);
resultPut = dpJoshi.simpleMC2(putPayOff, Expiry, Spot, Vol, r, NumberOfPaths);
resultDD = dpJoshi.simpleMC2(doubleDigitalPayOff, Expiry, Spot, Vol, r, NumberOfPaths);


In [11]:
resultCall

10.466119485719426

In [12]:
resultPut

5.560518126914602

In [13]:
resultDD

0.3177486769602185

# Chapter 4: Testing of SimpleMonteCarlo3 with Vanilla1 & PayOff classes

In [14]:
Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 1000000;

doubleDigitalPayOff = dpJoshi.PayOffDD(100,120)
theOption = dpJoshi.Vanilla1(doubleDigitalPayOff, Expiry)

In [15]:
resultDD = dpJoshi.simpleMC3(theOption, Spot, Vol, r, NumberOfPaths);
y = dpJoshi.Vanilla1(theOption)
resultDD = dpJoshi.simpleMC3(y, Spot, Vol, r, NumberOfPaths);

In [16]:
resultDD

0.3200401886438407

# Testing of SimpleMonteCarlo4 with Vanilla2 & PayOff3 classes

In [17]:
Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 1000000;

doubleDigitalPayOff = dpJoshi.PayOffDD3(100,120)
theOption = dpJoshi.Vanilla2(doubleDigitalPayOff, Expiry)

In [18]:
y = dpJoshi.Vanilla2(theOption)
resultDD_ = dpJoshi.simpleMC4(y, Spot, Vol, r, NumberOfPaths);
#resultDD_ = dpJoshi.simpleMC4(theOption, Spot, Vol, r, NumberOfPaths);


In [19]:
resultDD_

0.3202875082942109

# Testing of SimpleMonteCarlo5 with Vanilla3, PayOffBridge & PayOff3 classes

In [20]:
Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 1000000;

doubleDigitalPayOff = dpJoshi.PayOffDD3(100,120)
payOffBridgeDD = dpJoshi.PayOffBridge(doubleDigitalPayOff)
theOption = dpJoshi.Vanilla3(payOffBridgeDD, Expiry)

In [21]:
resultDD = dpJoshi.simpleMC5(theOption, Spot, Vol, r, NumberOfPaths);

In [22]:
resultDD

0.3203331673065869

# Testing of SimpleMonteCarlo6 with Vanilla3, PayOffBridge, PayOff3 & Parameters classes

In [23]:
Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 1000000;

In [24]:
doubleDigitalPayOff = dpJoshi.PayOffDD3(100,120)
payOffBridgeDD = dpJoshi.PayOffBridge(doubleDigitalPayOff)
theOption = dpJoshi.Vanilla3(payOffBridgeDD, Expiry)

VolParamCons = dpJoshi.ParametersConstant(Vol)
rParamCons = dpJoshi.ParametersConstant(r)

VolParam = dpJoshi.Parameters(VolParamCons)
rParam = dpJoshi.Parameters(rParamCons)


In [25]:
resultDD = dpJoshi.simpleMC6(theOption, Spot, VolParam, rParam, NumberOfPaths);

In [26]:
resultDD

0.3200487497086612

# Chapter 5: Testing of SimpleMonteCarlo7 MCStatistics class

In [27]:
Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 1000000;

In [28]:
doubleDigitalPayOff = dpJoshi.PayOffDD3(100,120)
payOffBridgeDD = dpJoshi.PayOffBridge(doubleDigitalPayOff)
theOption = dpJoshi.Vanilla3(payOffBridgeDD, Expiry)

VolParamCons = dpJoshi.ParametersConstant(Vol)
rParamCons = dpJoshi.ParametersConstant(r)

VolParam = dpJoshi.Parameters(VolParamCons)
rParam = dpJoshi.Parameters(rParamCons)

In [29]:
gatherer = dpJoshi.StatisticsMean()

In [30]:
dpJoshi.simpleMC7(theOption, Spot, VolParam, rParam, NumberOfPaths, gatherer);

In [31]:
gatherer.GetResultSoFar()

array([[0.31977289]])

# Testing of SimpleMonteCarlo7 MCStatistics & ConvergenceTable classes

In [32]:
Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 1000000;

In [33]:
doubleDigitalPayOff = dpJoshi.PayOffDD3(100,120)
payOffBridgeDD = dpJoshi.PayOffBridge(doubleDigitalPayOff)
theOption = dpJoshi.Vanilla3(payOffBridgeDD, Expiry)

VolParamCons = dpJoshi.ParametersConstant(Vol)
rParamCons = dpJoshi.ParametersConstant(r)

VolParam = dpJoshi.Parameters(VolParamCons)
rParam = dpJoshi.Parameters(rParamCons)

In [34]:
gatherer = dpJoshi.StatisticsMean()

In [35]:
wrapper = dpJoshi.WrapperStats(gatherer)
gathererTwo = dpJoshi.ConvergenceTable(wrapper)

In [36]:
dpJoshi.simpleMC7(theOption, Spot, VolParam, rParam, NumberOfPaths, gathererTwo);

In [37]:
gathererTwo.GetResultSoFar()

array([[0.00000000e+00, 2.00000000e+00],
       [2.37807356e-01, 4.00000000e+00],
       [2.37807356e-01, 8.00000000e+00],
       [3.56711034e-01, 1.60000000e+01],
       [3.56711034e-01, 3.20000000e+01],
       [3.12122155e-01, 6.40000000e+01],
       [2.82396235e-01, 1.28000000e+02],
       [3.04690675e-01, 2.56000000e+02],
       [2.95401325e-01, 5.12000000e+02],
       [3.14908960e-01, 1.02400000e+03],
       [3.19553635e-01, 2.04800000e+03],
       [3.18856934e-01, 4.09600000e+03],
       [3.19089167e-01, 8.19200000e+03],
       [3.18276349e-01, 1.63840000e+04],
       [3.18653729e-01, 3.27680000e+04],
       [3.20293880e-01, 6.55360000e+04],
       [3.21636481e-01, 1.31072000e+05],
       [3.21233701e-01, 2.62144000e+05],
       [3.20366453e-01, 5.24288000e+05],
       [3.20558609e-01, 1.00000000e+06]])

# Chapter 6: Testing of SimpleMonteCarlo8 & random numbers generator

In [38]:
Expiry = 1.;
Spot = 100;
Vol = 0.2;
r = 0.05;
NumberOfPaths = 1000000;

In [39]:
doubleDigitalPayOff = dpJoshi.PayOffDD3(100,120)
payOffBridgeDD = dpJoshi.PayOffBridge(doubleDigitalPayOff)
theOption = dpJoshi.Vanilla3(payOffBridgeDD, Expiry)

VolParamCons = dpJoshi.ParametersConstant(Vol)
rParamCons = dpJoshi.ParametersConstant(r)

VolParam = dpJoshi.Parameters(VolParamCons)
rParam = dpJoshi.Parameters(rParamCons)

In [40]:
gatherer = dpJoshi.StatisticsMean()
wrapper = dpJoshi.WrapperStats(gatherer)
gathererTwo = dpJoshi.ConvergenceTable(wrapper)

In [41]:
generator = dpJoshi.RandomParkMiller(1,1)
wrapper2 = dpJoshi.WrapperRandom(generator)
genTwo = dpJoshi.Antithetic(wrapper2)

In [42]:
dpJoshi.simpleMC8(theOption, Spot, VolParam, rParam, NumberOfPaths, gathererTwo, genTwo);

In [43]:
gathererTwo.GetResultSoFar()

array([[0.00000000e+00, 2.00000000e+00],
       [0.00000000e+00, 4.00000000e+00],
       [3.56711034e-01, 8.00000000e+00],
       [3.56711034e-01, 1.60000000e+01],
       [3.56711034e-01, 3.20000000e+01],
       [3.41848074e-01, 6.40000000e+01],
       [3.64142514e-01, 1.28000000e+02],
       [3.49279554e-01, 2.56000000e+02],
       [3.41848074e-01, 5.12000000e+02],
       [3.47421684e-01, 1.02400000e+03],
       [3.44170412e-01, 2.04800000e+03],
       [3.29307452e-01, 4.09600000e+03],
       [3.25243362e-01, 8.19200000e+03],
       [3.21295388e-01, 1.63840000e+04],
       [3.17666736e-01, 3.27680000e+04],
       [3.21396990e-01, 6.55360000e+04],
       [3.21803399e-01, 1.31072000e+05],
       [3.21019610e-01, 2.62144000e+05],
       [3.20312023e-01, 5.24288000e+05],
       [3.19879431e-01, 1.00000000e+06]])

# Chapter 7: Asian Options & Stuff

## Testing MJArray interface with numpy

In [44]:
y = np.array([1,2,3,4,5,6,7,8,9,10]).astype(np.float64)

In [45]:
z = dpJoshi.MJArray(y)

In [46]:
for i in range(z.size()):
    print(z[i])

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [47]:
Expiry = 1.;
Strike = 29;
Spot = 30;
Vol = 0.3;
r = 0.08;
d = 0;
    
NumberOfPaths = 1000000;
NumberOfDates = 250;
   
thePayOff = dpJoshi.PayOffCall3(Strike);
payOffBridge = dpJoshi.PayOffBridge(thePayOff)
times = dpJoshi.MJArray(NumberOfDates);

for i in range(NumberOfDates):
    
    times[i] = (i+1.)*Expiry/NumberOfDates;


# BSEngine in action with Asian call :)

In [48]:
VolParamCons = dpJoshi.ParametersConstant(Vol);
rParamCons = dpJoshi.ParametersConstant(r);
dParamCons = dpJoshi.ParametersConstant(d);

VolParam = dpJoshi.Parameters(VolParamCons)
rParam = dpJoshi.Parameters(rParamCons)
dParam = dpJoshi.Parameters(dParamCons);


In [49]:
theOption = dpJoshi.PathDependentAsian(times, Expiry, payOffBridge)
gatherer = dpJoshi.StatisticsMean()
wrapper = dpJoshi.WrapperStats(gatherer)
gathererTwo = dpJoshi.ConvergenceTable(wrapper)

generator = dpJoshi.RandomParkMiller(NumberOfDates,1)
wrapper2 = dpJoshi.WrapperRandom(generator)
genTwo = dpJoshi.Antithetic(wrapper2)

wrapper3 = dpJoshi.WrapperPathDependent(theOption)


In [50]:
theEngine = dpJoshi.ExoticBSEngine(wrapper3, rParam, dParam, VolParam, wrapper2, Spot);

In [51]:
theEngine.DoSimulation(gathererTwo, NumberOfPaths)

In [52]:
gathererTwo.GetResultSoFar()

array([[5.50635806e-01, 2.00000000e+00],
       [4.65171400e-01, 4.00000000e+00],
       [3.15283060e+00, 8.00000000e+00],
       [2.95459710e+00, 1.60000000e+01],
       [3.16939494e+00, 3.20000000e+01],
       [3.57115142e+00, 6.40000000e+01],
       [3.51289290e+00, 1.28000000e+02],
       [3.23713353e+00, 2.56000000e+02],
       [3.19466253e+00, 5.12000000e+02],
       [3.21961731e+00, 1.02400000e+03],
       [2.95286559e+00, 2.04800000e+03],
       [3.11413667e+00, 4.09600000e+03],
       [3.16807781e+00, 8.19200000e+03],
       [3.15954830e+00, 1.63840000e+04],
       [3.14625723e+00, 3.27680000e+04],
       [3.13368986e+00, 6.55360000e+04],
       [3.13482017e+00, 1.31072000e+05],
       [3.14685176e+00, 2.62144000e+05],
       [3.14141547e+00, 5.24288000e+05],
       [3.14078314e+00, 1.00000000e+06]])

# Chapter 8: Trees

In [3]:
Expiry = 1.;
Strike = 100;
Spot = 100;
Vol = 0.2;
r = 0.05;
d = 0;
Steps = 1000;

thePayOff = dpJoshi.PayOffCall3(Strike);
payOffBridge = dpJoshi.PayOffBridge(thePayOff)
    
rParamCons = dpJoshi.ParametersConstant(r);
dParamCons = dpJoshi.ParametersConstant(d);

rParam = dpJoshi.Parameters(rParamCons)
dParam = dpJoshi.Parameters(dParamCons);   

In [4]:
euroOption = dpJoshi.TreeEuropean(Expiry, payOffBridge);
theTree = dpJoshi.SimpleBinomialTree(Spot, rParam, dParam, Vol, Steps, Expiry);

In [5]:
theTree.GetThePrice(euroOption)

10.4521793486298

In [6]:
fwdPayOff = dpJoshi.PayOffForward(Strike)
fwdPayOffBridge = dpJoshi.PayOffBridge(fwdPayOff)

In [7]:
fwd = dpJoshi.TreeEuropean(Expiry, fwdPayOffBridge)
theTree.GetThePrice(fwd)

4.877044216738232

In [8]:
actualFwdPrice = np.exp(-r*Expiry)*(Spot*np.exp((r-d)*Expiry)-Strike)

In [9]:
actualFwdPrice

4.877057549928611

In [11]:
BSPrice = dpJoshi.BlackScholesCall(Spot, Strike, r, d, Vol, Expiry);

In [12]:
BSPrice

10.450575619322287